1  Programming failure          :
10 ERRORS OCCURRED !!!!!!!!!!!!!!
11 Freestore exceeded           :
12 Can't read file              :
13 Can't write in file          :
14 Run stopped at interval      :
15 Missing TS-Data for interval :
16 Error reading file           :
17 Error writing in file        :
18 Something wrong in interval  :
19 Scanning parameter not used  :
20 Scanning and creating extensive result files is incompatible:
21 Use of not-fully defined virtual function:
22 Reading of expected "," impossible:
23 Can't clear file             :
24 Can't insert process in graph:
25 Can't find process type      :
26 Can't insert balance in graph:
27 Can't find balance type      :
28 Can't insert flow in graph   :
29 Can't find balance of connection:
30 Can't find process of connection:
31 Cycle found including process:
32 No connection found          :
33 More than 1 connection found :
34 More than 1 process connected:
35 Edge not connected to a process entry or exit:
36 Explicit connection with "El":
37 Output of intensive variables (attributes) not determined:
38 Edges of the cycle           :
39 Energy flow type or link type not compatible with balance type:
40 More than one entering energy flow not allowed for:
41 More than one leaving energy flow not allowed for:
42 More than one leaving or entering energy flow not allowed for:
43 No entering or no leaving energy flow detected for:
44 Balance type is not a legal one:
45 (Simplex), Unbounded objective function detected at interval:
46 (Simplex), No solutions satisfy constraints given in interval:
47 Process of process aggregate not found in process list:
48 Some objective function coefficients are missing:
49 No constraint or only one energy flow detected
50 Math-library function error  :
51 Floating point error (invalid operation, divide-by-zero or overflow)
52 Freestore exceeded
53 Negative inequalities are not allowed for process aggregates:
54 Missing attribute detected   :
55 Missing process input parameter:
56 Some input parameters are zero or negative :
57 Missing environment data     :
58 Missing process input time series data:
59 Process aggregation forbidden:
60 Return temperature is larger than flow temperature:
61 Inconsistent input parameter :
62 Environment data out of range:
63 Return temperature is not determined (heat flow usage):
64 Routine should not be used   :
65 Unexpected negative or zero value during run:
67 Input parameter is negative  :
68 Time series input data is negative:
69 Attribute is zero or negative:
70 No solution found for        :
501 Can't run scenario           :
502 Unexpected end of scenario   :
503 Standard version used of (virtual function not overwritten?):
504 Math-library function problem:
505 Input parameters are zero or negative (a floating point error may occur):
506 Divide by a zero approaching value:
507 Tried to take log of a zero approaching value:
1000                              :
1001 Constructor                  :
1002 Destructor                   :
1003 User time                    :
1004 Real time                    :
1005 End of
1006 End of scenario              :
1009 Definition values            :
1010 Input parameter values       :
1011 Input file read              :
1012 Output file written          :
1013 Old input overwritten with   :
1014 Vertices of the graph        :
1015 Edges of the graph           :
1016 Sorted process list          :
1017 You interrupted the program. If you think the program is hanging in an endless loop, see the user manual.
1018 Interval number:

